-- CreateEnum: FeatureAccess for permission system
CREATE TYPE "FeatureAccess" AS ENUM (
  'LEADS_READ',
  'LEADS_WRITE',
  'LEADS_DELETE',
  'LEADS_EXPORT',
  'LEADS_BULK_ACTIONS',
  'LEADS_ASSIGN',
  'PROPERTIES_READ',
  'PROPERTIES_WRITE',
  'PROPERTIES_DELETE',
  'PROPERTIES_PUBLISH',
  'PROPERTIES_ASSIGN_AGENT',
  'PROPERTIES_IMPORT',
  'CAMPAIGNS_READ',
  'CAMPAIGNS_WRITE',
  'CAMPAIGNS_DELETE',
  'CAMPAIGNS_ACTIVATE',
  'CAMPAIGNS_VIEW_ANALYTICS',
  'CAMPAIGNS_MANAGE_BUDGET',
  'AUTOMATIONS_READ',
  'AUTOMATIONS_WRITE',
  'AUTOMATIONS_DELETE',
  'AUTOMATIONS_EXECUTE',
  'INTEGRATIONS_READ',
  'INTEGRATIONS_WRITE',
  'INTEGRATIONS_DELETE',
  'INTEGRATIONS_SYNC',
  'REPORTS_VIEW_BASIC',
  'REPORTS_VIEW_ADVANCED',
  'REPORTS_EXPORT',
  'REPORTS_SCHEDULE',
  'REPORTS_CUSTOM',
  'ORG_SETTINGS',
  'ORG_BILLING',
  'ORG_MEMBERS_READ',
  'ORG_MEMBERS_WRITE',
  'ORG_MEMBERS_DELETE',
  'ORG_INVITE_MEMBERS',
  'API_ACCESS',
  'WHITE_LABEL',
  'CUSTOM_INTEGRATIONS',
  'DEDICATED_SUPPORT',
  'BULK_OPERATIONS',
  'ADVANCED_ANALYTICS'
);

-- AlterTable: Add custom permissions to Membership
ALTER TABLE "Membership" ADD COLUMN "customPermissions" JSONB;
ALTER TABLE "Membership" ADD COLUMN "invitedBy" TEXT;
ALTER TABLE "Membership" ADD COLUMN "joinedAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP;

-- Update existing records to have joinedAt = createdAt if null
UPDATE "Membership" SET "joinedAt" = "createdAt" WHERE "joinedAt" IS NULL;

-- CreateIndex: Add indexes for role and status on Membership
CREATE INDEX "Membership_role_idx" ON "Membership"("role");
CREATE INDEX "Membership_status_idx" ON "Membership"("status");

-- CreateIndex: Add index for plan on Subscription
CREATE INDEX "Subscription_plan_idx" ON "Subscription"("plan");

-- CreateTable: PlanPermissions for plan-based permission configuration
CREATE TABLE "PlanPermissions" (
    "id" TEXT NOT NULL,
    "plan" "SubscriptionPlan" NOT NULL,
    "permissions" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PlanPermissions_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "PlanPermissions_plan_key" ON "PlanPermissions"("plan");
CREATE INDEX "PlanPermissions_plan_idx" ON "PlanPermissions"("plan");

-- Seed default plan permissions
INSERT INTO "PlanPermissions" ("id", "plan", "permissions", "createdAt", "updatedAt")
VALUES
  (
    gen_random_uuid()::text,
    'BASIC',
    '["LEADS_READ", "LEADS_WRITE", "PROPERTIES_READ", "PROPERTIES_WRITE", "CAMPAIGNS_READ", "REPORTS_VIEW_BASIC", "INTEGRATIONS_READ", "ORG_MEMBERS_READ"]'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    gen_random_uuid()::text,
    'PRO',
    '["LEADS_READ", "LEADS_WRITE", "LEADS_DELETE", "LEADS_EXPORT", "LEADS_BULK_ACTIONS", "LEADS_ASSIGN", "PROPERTIES_READ", "PROPERTIES_WRITE", "PROPERTIES_DELETE", "PROPERTIES_PUBLISH", "PROPERTIES_ASSIGN_AGENT", "PROPERTIES_IMPORT", "CAMPAIGNS_READ", "CAMPAIGNS_WRITE", "CAMPAIGNS_DELETE", "CAMPAIGNS_ACTIVATE", "CAMPAIGNS_VIEW_ANALYTICS", "AUTOMATIONS_READ", "AUTOMATIONS_WRITE", "AUTOMATIONS_EXECUTE", "INTEGRATIONS_READ", "INTEGRATIONS_WRITE", "INTEGRATIONS_SYNC", "REPORTS_VIEW_BASIC", "REPORTS_VIEW_ADVANCED", "REPORTS_EXPORT", "ORG_MEMBERS_READ"]'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    gen_random_uuid()::text,
    'AGENCY',
    '["LEADS_READ", "LEADS_WRITE", "LEADS_DELETE", "LEADS_EXPORT", "LEADS_BULK_ACTIONS", "LEADS_ASSIGN", "PROPERTIES_READ", "PROPERTIES_WRITE", "PROPERTIES_DELETE", "PROPERTIES_PUBLISH", "PROPERTIES_ASSIGN_AGENT", "PROPERTIES_IMPORT", "CAMPAIGNS_READ", "CAMPAIGNS_WRITE", "CAMPAIGNS_DELETE", "CAMPAIGNS_ACTIVATE", "CAMPAIGNS_VIEW_ANALYTICS", "CAMPAIGNS_MANAGE_BUDGET", "AUTOMATIONS_READ", "AUTOMATIONS_WRITE", "AUTOMATIONS_DELETE", "AUTOMATIONS_EXECUTE", "INTEGRATIONS_READ", "INTEGRATIONS_WRITE", "INTEGRATIONS_DELETE", "INTEGRATIONS_SYNC", "REPORTS_VIEW_BASIC", "REPORTS_VIEW_ADVANCED", "REPORTS_EXPORT", "REPORTS_SCHEDULE", "REPORTS_CUSTOM", "ORG_SETTINGS", "ORG_INVITE_MEMBERS", "ORG_MEMBERS_READ", "ORG_MEMBERS_WRITE", "API_ACCESS", "WHITE_LABEL", "BULK_OPERATIONS", "ADVANCED_ANALYTICS"]'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    gen_random_uuid()::text,
    'ENTERPRISE',
    '["LEADS_READ", "LEADS_WRITE", "LEADS_DELETE", "LEADS_EXPORT", "LEADS_BULK_ACTIONS", "LEADS_ASSIGN", "PROPERTIES_READ", "PROPERTIES_WRITE", "PROPERTIES_DELETE", "PROPERTIES_PUBLISH", "PROPERTIES_ASSIGN_AGENT", "PROPERTIES_IMPORT", "CAMPAIGNS_READ", "CAMPAIGNS_WRITE", "CAMPAIGNS_DELETE", "CAMPAIGNS_ACTIVATE", "CAMPAIGNS_VIEW_ANALYTICS", "CAMPAIGNS_MANAGE_BUDGET", "AUTOMATIONS_READ", "AUTOMATIONS_WRITE", "AUTOMATIONS_DELETE", "AUTOMATIONS_EXECUTE", "INTEGRATIONS_READ", "INTEGRATIONS_WRITE", "INTEGRATIONS_DELETE", "INTEGRATIONS_SYNC", "REPORTS_VIEW_BASIC", "REPORTS_VIEW_ADVANCED", "REPORTS_EXPORT", "REPORTS_SCHEDULE", "REPORTS_CUSTOM", "ORG_SETTINGS", "ORG_BILLING", "ORG_INVITE_MEMBERS", "ORG_MEMBERS_READ", "ORG_MEMBERS_WRITE", "ORG_MEMBERS_DELETE", "API_ACCESS", "WHITE_LABEL", "CUSTOM_INTEGRATIONS", "DEDICATED_SUPPORT", "BULK_OPERATIONS", "ADVANCED_ANALYTICS"]'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  )
ON CONFLICT (plan) DO NOTHING;
